apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
    containers:
      - image: peter3636/flaskapp:v1
        name: todo-app
        ports:
        - containerPort: 8090
